export const parentStrings = {
  dashboard: {
    eyebrow: "יום שני, 11 במרץ",
    title: "בוקר טוב, אגם 👋",
    description: "הנה כל מה שקורה עם המשפחה שלך היום.",
    attentionTitle: "יש 3 פריטים שמחכים לתשומת הלב שלך",
    attentionDescription: "משימה אחת להגשה מחר ולדניאל יש משימה באיחור.",
    attentionHeading: "דורש תשומת לב",
    attentionSubheading: "דברים חשובים שכדאי לשים לב אליהם.",
    upcomingHeading: "מה בקרוב",
    upcomingSubheading: "לוח הזמנים המשפחתי לשבוע הקרוב.",
    progressHeading: "התקדמות שבועית",
    progressSubheading: "משימות שהושלמו השבוע.",
    progressAction: "למעקב אחר התקדמות",
    announcementLabel: "עדכון בית ספרי",
    announcementTitle: "יום הקריאה המשפחתי יתקיים ביום חמישי",
    announcementText: "נשמח לפגוש אתכם בספריית בית הספר לסיפורים, פעילויות ואורח מיוחד.",
    announcementAction: "לקריאה נוספת ←",
  },
  assignments: {
    eyebrow: "למידה משפחתית",
    title: "משימות",
    description: "כאן אפשר לעקוב אחר כל משימה, מועד והישג.",
    download: "◫ הורדת סיכום",
  },
  exams: {
    eyebrow: "להיות מוכנים",
    title: "מבחנים קרובים",
    description: "כל מה שהילדים צריכים כדי להגיע מוכנים.",
    inTwoDays: "בעוד יומיים",
    materials: "חומרי לימוד",
    studyMaterials: "לחומרי הלימוד ←",
  },
  calendar: { eyebrow: "לוח זמנים משפחתי", title: "לוח שנה" },
  messages: {
    eyebrow: "שיחות",
    title: "הודעות",
    description: "תקשורת פשוטה עם המורים של הילדים.",
    newMessage: "+ הודעה חדשה",
    search: "חיפוש הודעות",
    compose: "כתיבת הודעה...",
  },
} as const;
